[package]
name = "termd"
version = "0.1.0"
authors = ["Zbigniew Kostrzewa <zkostrzewa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
termimad = "0.8.17"
notify = "5.0.0-pre.2"